name: Terraform CI/CD
on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main
jobs:
  terraform-plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Terrraform
        uses: hashicorp/setup-terraform@v3 
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2
          role-session-name: github-actions
      - name: Terraform Init
        run: terraform init
        working-directory: asg-django-app
      - name: Terraform plan
        run: terraform plan 
        working-directory: asg-django-app
  terraform-apply:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Terrraform
        uses: hashicorp/setup-terraform@v3 
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2
          role-session-name: github-actions
      - name: Terraform Init
        run: terraform init
        working-directory: asg-django-app
      - name: Terraform apply
        run: terraform apply --auto-approve
        working-directory: asg-django-app